// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrAlS8l1w_pLqmekaFZhOMVSaeGwEpkY',
    appId: '1:229341096461:web:40bac0167d141cd1720344',
    messagingSenderId: '229341096461',
    projectId: 'crud-7055e',
    authDomain: 'crud-7055e.firebaseapp.com',
    storageBucket: 'crud-7055e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoXx2_bDUSdCPvQ4P_erTuzha2bXDPVU0',
    appId: '1:229341096461:ios:c077f87e8457453b720344',
    messagingSenderId: '229341096461',
    projectId: 'crud-7055e',
    storageBucket: 'crud-7055e.firebasestorage.app',
    iosBundleId: 'com.example.firepower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoXx2_bDUSdCPvQ4P_erTuzha2bXDPVU0',
    appId: '1:229341096461:ios:c077f87e8457453b720344',
    messagingSenderId: '229341096461',
    projectId: 'crud-7055e',
    storageBucket: 'crud-7055e.firebasestorage.app',
    iosBundleId: 'com.example.firepower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPrAlS8l1w_pLqmekaFZhOMVSaeGwEpkY',
    appId: '1:229341096461:web:d5ae364bf43cf0a8720344',
    messagingSenderId: '229341096461',
    projectId: 'crud-7055e',
    authDomain: 'crud-7055e.firebaseapp.com',
    storageBucket: 'crud-7055e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmicOhnjVoPkzIVLRiqyPjmNna_PLwAA',
    appId: '1:229341096461:android:f25a4a1d4ae31169720344',
    messagingSenderId: '229341096461',
    projectId: 'crud-7055e',
    storageBucket: 'crud-7055e.firebasestorage.app',
  );

}